services:
  database:
    image: postgres:15
    restart: always
    env_file:
      - .base.env
      - .docker-compose.env
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: not-needed@example.com
      PGADMIN_DEFAULT_PASSWORD: not-needed
    ports:
      - '8888:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  database-migrations:
    restart: no
    depends_on:
      database:
        condition: service_started
    image: service-catalog-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .base.env
      - .docker-compose.env
    command: npx typeorm migration:run --dataSource=database/dataSource.js

  api:
    depends_on:
      database-migrations:
        condition: service_completed_successfully
    image: service-catalog-api
    env_file:
      - .base.env
      - .docker-compose.env
    environment:
      PORT: 3000
    ports:
      - '80:3000'

volumes:
  database_data:
  pgadmin_data:
